name: zpoint_large_embedding_zh
model_path: '/data/share/storage/checkpoint/text_encoder/zpoint_large_embedding_zh/models--iampanda--zpoint_large_embedding_zh/snapshots/b1075144f440ab4409c05622c1179130ebd57d03'
