name: siglip
model_path:
  base: '/data/share/storage/checkpoint/image_encoder/SigLIP/models--google--siglip-base-patch16-224/snapshots/7fd15f0689c79d79e38b1c2e2e2370a7bf2761ed'
  large: '/data/share/storage/checkpoint/image_encoder/SigLIP/models--google--siglip-large-patch16-384/snapshots/ce005573a40965dfd21fd937fbdeeebf2439fc35'
  so400m: '/data/share/storage/checkpoint/image_encoder/SigLIP/models--google--siglip-so400m-patch14-384/snapshots/9fdffc58afc957d1a03a25b10dba0329ab15c2a3'